<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="copyRegistration.aspx.cs" Inherits="Sarasavi.copyRegistration" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div class="BookCopy">
<!-- Copy Registration -->
 <fieldset class = "breg1">

<legend>Copy Registration</legend>
<form name="form2">

    <asp:Label ID="lblErr" runat="server" Font-Size="X-Large" ForeColor="White"></asp:Label>
    <br />
    <asp:Label ID="lblISBNcp" runat="server" Text="ISBN" ForeColor="White"></asp:Label>
    <br />
    <asp:TextBox ID="txtISBN" runat="server" Height="30px" Width="368px" 
        ontextchanged="txtISBN_TextChanged"></asp:TextBox>
    </form>
    <br />
    <br />
    <form name="form3">
    <asp:Label ID="lblBookTitile" runat="server" Text="Book Title" 
        ForeColor="White"></asp:Label>
    <br />
    <asp:Label ID="txtTitle" runat="server" Font-Bold="True" Font-Size="Large" 
        ForeColor="White"></asp:Label>
    <br />
    

    <br />
    <asp:Label ID="lblCopyISBN" runat="server" Text="Copy ISBN" ForeColor="White"></asp:Label>
    <br />
    <asp:Label ID="txtCopyISBN" runat="server" Font-Bold="True" Font-Size="Large" 
        ForeColor="White"></asp:Label>
    <br />
    <br />

    <asp:Label ID="Label14" runat="server" ForeColor="White" 
        Text="Copy Type"></asp:Label>
    <br />
    <asp:DropDownList ID="ddlCopyType" runat="server" Height="50px" Width="360px">
        <asp:ListItem>Borrowed</asp:ListItem>
        <asp:ListItem>Reserved</asp:ListItem>
    </asp:DropDownList>
    <br />
    <br />
    <!--It might be an autogenerated one-->
  </form>

    <asp:Button ID="btnCopyReg1" runat="server" onclick="btnCopyReg1_Click" 
        Text="Register Copy" BackColor="#009900" Height="51px" Width="370px" />
</form>
</fieldset>
</div>
</asp:Content>
